language: python
python:
  - 3.6
env:
  - "PIP_NO_BINARY=:all:"
install:
  - pip install -U pip pipenv
  - pipenv install --dev --system
before_script:
  - python manage.py migrate
script:
  - coverage run manage.py test --parallel
